# Generated by Django 4.2.1 on 2023-05-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0002_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombreC',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(db_comment='Apellidos del cliente', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(db_comment='Nombres del cliente', max_length=55, null=True),
        ),
    ]
