# Generated by Django 4.2.1 on 2023-05-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0003_remove_cliente_nombrec_cliente_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numeroCelular',
            field=models.CharField(db_comment='Numero de celular del cliente', max_length=55, unique=True),
        ),
    ]
