# Generated by Django 4.2.1 on 2023-05-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0004_alter_cliente_numerocelular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(db_comment='Placa del vehiculo', max_length=6, unique=True)),
                ('marca', models.CharField(db_comment='Marca del vehiculo', max_length=15)),
                ('tipo', models.CharField(choices=[('Electrico', 'Electrico'), ('Gasolina', 'Gasolina')], db_comment='Tipo de vehiculo', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(db_comment='Correo del cliente', max_length=55),
        ),
    ]
