# Generated by Django 4.2.1 on 2023-05-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0005_vehiculo_alter_cliente_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(db_comment='Modelo del vehiculo', max_length=15, null=True),
        ),
    ]
