# Generated by Django 4.2.1 on 2023-05-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0006_vehiculo_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(db_comment='Identificacion del empleado', max_length=55, unique=True)),
                ('nombres', models.CharField(db_comment='Nombres del empleado', max_length=55, null=True)),
                ('apellidos', models.CharField(db_comment='Apellidos del empleado', max_length=55, null=True)),
                ('correo', models.CharField(db_comment='Correo del cliente', max_length=55)),
                ('numeroCelular', models.CharField(db_comment='Numero de celular del empleado', max_length=55, unique=True)),
                ('cargo', models.CharField(db_comment='Cargo del empleado', max_length=30, unique=True)),
                ('sueldo', models.IntegerField(db_comment='Suelo del empleado')),
            ],
        ),
    ]
