# Generated by Django 4.2.1 on 2023-05-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0007_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_comment='Tipo de vehiculo', max_length=15, null=True),
        ),
    ]
