# Generated by Django 4.2.1 on 2023-05-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0008_empleado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_comment='Estado del empleado', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='identificacion',
            field=models.CharField(db_comment='Identificacion del empleado', max_length=15, unique=True),
        ),
    ]
