# Generated by Django 4.2.1 on 2023-05-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0009_alter_empleado_estado_alter_empleado_identificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perIdentificacion', models.CharField(db_comment='Identificacion de la persona', max_length=15, unique=True)),
                ('perNombres', models.CharField(db_comment='Nombres de la persona', max_length=55, null=True)),
                ('perApellidos', models.CharField(db_comment='Apellidos de la persona', max_length=55, null=True)),
                ('perCorreo', models.CharField(db_comment='Correo de la persona', max_length=55)),
                ('perNumeroCelular', models.CharField(db_comment='Numero de celular de la persona', max_length=55, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='cargo',
            new_name='empCargo',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='estado',
            new_name='empEstado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='sueldo',
            new_name='empSueldo',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='marca',
            new_name='vehMarca',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='modelo',
            new_name='vehModelo',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='placa',
            new_name='vehPlaca',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='tipo',
            new_name='vehTipo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numeroCelular',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='numeroCelular',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliDireccion',
            field=models.CharField(db_comment='Direccion del cliente', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliPersona',
            field=models.ForeignKey(db_comment='Hace relación a la persona FK', null=True, on_delete=django.db.models.deletion.PROTECT, to='appGestionServiteca.persona'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='empPersona',
            field=models.ForeignKey(db_comment='Hace relación a la persona FK', default=None, on_delete=django.db.models.deletion.PROTECT, to='appGestionServiteca.persona'),
        ),
    ]
