# Generated by Django 4.2.3 on 2023-08-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0011_servicio_alter_cliente_clipersona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliDireccion',
            field=models.CharField(db_comment='Direccion del cliente', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliPersona',
            field=models.ForeignKey(db_comment='Hace relación a la persona FK', on_delete=django.db.models.deletion.PROTECT, to='appGestionServiteca.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='perApellidos',
            field=models.CharField(db_comment='Apellidos de la persona', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='perCorreo',
            field=models.CharField(db_comment='Correo de la persona', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='perIdentificacion',
            field=models.CharField(db_comment='Identificacion de la persona', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='perNombres',
            field=models.CharField(db_comment='Nombres de la persona', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='perNumeroCelular',
            field=models.CharField(db_comment='Numero de celular de la persona', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='serFechaFinal',
            field=models.DateTimeField(auto_now_add=True, db_comment='Fecha y Hora ultima actualizacion del servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='serNombre',
            field=models.CharField(db_comment='Nombre del servicio', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='vehMarca',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Nissan', 'Nissan'), ('Mazda', 'Mazda'), ('Hyundai', 'Hyundai'), ('Chevrolet', 'Chevrolet'), ('BMW', 'BMW'), ('Suzuki', 'Suzuki'), ('Ford', 'Ford'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Renault', 'Renault'), ('Kia', 'Kia'), ('Honda', 'Honda'), ('Jeep', 'Jeep'), ('Volkswagen', 'Volkswagen'), ('Ssangyong', 'Ssangyong'), ('Fiat', 'Fiat'), ('Lexus', 'Lexus'), ('Citroën', 'Citroën'), ('Jac', 'Jac'), ('Mitsubishi', 'Mitsubishi')], db_comment='Marca del vehiculo', max_length=27),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='vehModelo',
            field=models.IntegerField(db_comment='Modelo del vehiculo', null=True),
        ),
        migrations.CreateModel(
            name='ServicioPrestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serpObservaciones', models.TextField(db_comment='Novedad acerca del servicio prestado realizado', null=True)),
                ('serpFechaServicio', models.DateTimeField(auto_now_add=True, db_comment='Fecha y Hora ultima actualizacion del servicio prestado')),
                ('serpCli', models.ForeignKey(db_comment='Hace relación al cliente FK', on_delete=django.db.models.deletion.PROTECT, to='appGestionServiteca.cliente')),
                ('serpVehi', models.ForeignKey(db_comment='Hace relación al vehiculo FK', on_delete=django.db.models.deletion.PROTECT, to='appGestionServiteca.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facTotal', models.IntegerField(db_comment='Total del costo de todos los servicios prestados.')),
                ('facEstado', models.CharField(choices=[('Pagada', 'Pagada'), ('No Pagada', 'No Pagada')], db_comment='Estado de la factura', max_length=13)),
                ('facCodigo', models.CharField(choices=[('SVP', 'Servicio Prestado')], db_comment='Codigo factura', max_length=3)),
                ('facFecha', models.DateTimeField(auto_now_add=True, db_comment='Fecha y Hora de la factura')),
                ('facServicioPrestado', models.ForeignKey(db_comment='Hace relación al servicio prestado FK', on_delete=django.db.models.deletion.PROTECT, to='appGestionServiteca.servicioprestado')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleServicioPrestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detServicio', models.ForeignKey(db_comment='Hace relación al servicio FK', on_delete=django.db.models.deletion.PROTECT, to='appGestionServiteca.servicio')),
                ('detServicioPrestado', models.ForeignKey(db_comment='Hace relación al servicio FK', on_delete=django.db.models.deletion.PROTECT, to='appGestionServiteca.servicioprestado')),
                ('serpEmp', models.ForeignKey(db_comment='Hace relación al empleado FK', on_delete=django.db.models.deletion.PROTECT, to='appGestionServiteca.empleado')),
            ],
        ),
    ]
