# Generated by Django 4.2.3 on 2023-08-18 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0012_alter_cliente_clidireccion_alter_cliente_clipersona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='vehMarca',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Nissan', 'Nissan'), ('Mazda', 'Mazda'), ('Hyundai', 'Hyundai'), ('Chevrolet', 'Chevrolet'), ('BMW', 'BMW'), ('Suzuki', 'Suzuki'), ('Ford', 'Ford'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Renault', 'Renault'), ('Kia', 'Kia'), ('Honda', 'Honda'), ('Jeep', 'Jeep'), ('Volkswagen', 'Volkswagen'), ('Ssangyong', 'Ssangyong'), ('Fiat', 'Fiat'), ('Lexus', 'Lexus'), ('Citroën', 'Citroën'), ('Jac', 'Jac'), ('Mitsubishi', 'Mitsubishi'), ('Cadillac', 'Cadillac'), ('Dodge', 'Dodge')], db_comment='Marca del vehiculo', max_length=27),
        ),
        migrations.CreateModel(
            name='PeticionForgot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro de la peticion forgot')),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], db_comment='Estado de la peticion forgot', default='Activa', max_length=27)),
                ('id_user', models.ForeignKey(db_comment='Hace relación al usuario FK', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
