# Generated by Django 4.2.3 on 2023-08-18 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0014_delete_peticionforgot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeticionForgot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro de la peticion forgot')),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], db_comment='Estado de la peticion forgot', default='Activa', max_length=27)),
                ('id_user', models.ForeignKey(db_comment='Hace relación al usuario FK', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
