# Generated by Django 4.2.3 on 2023-08-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0016_alter_factura_faccodigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioprestado',
            name='serpEstado',
            field=models.CharField(choices=[('Cancelado', 'Cancelado'), ('Solicitado', 'Solicitado'), ('Terminado', 'Terminado'), ('Entregado', 'Entregado')], db_comment='Estado del servicio prestado', max_length=10, null=True),
        ),
    ]
