# Generated by Django 4.2.3 on 2023-08-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0017_servicioprestado_serpestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliDireccion',
            field=models.CharField(db_comment='Direccion del cliente', max_length=72, null=True),
        ),
    ]
