# Generated by Django 4.2.3 on 2023-08-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0018_alter_cliente_clidireccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='facCodigo',
            field=models.CharField(choices=[('SVP', 'SVP')], db_comment='Codigo factura', max_length=10),
        ),
    ]
