# Generated by Django 4.2.3 on 2023-08-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0019_alter_factura_faccodigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleservicioprestado',
            old_name='serpEmp',
            new_name='detEmpleado',
        ),
    ]
