# Generated by Django 4.2.3 on 2023-09-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0022_alter_servicioprestado_serpestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioprestado',
            name='serpEstado',
            field=models.CharField(choices=[('Cancelado', 'Cancelado'), ('Solicitado', 'Solicitado'), ('Terminado', 'Terminado'), ('Entregado', 'Entregado'), ('En Proceso', 'En Proceso'), ('Realizado', 'Realizado')], db_comment='Estado del servicio prestado', max_length=15, null=True),
        ),
    ]
