# Generated by Django 4.2.3 on 2023-10-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0024_servicio_estadoservicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estadoServicio',
            field=models.CharField(choices=[('En Proceso', 'En Proceso'), ('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado')], db_comment='Estado del servicio', max_length=15),
        ),
    ]
