# Generated by Django 4.2.3 on 2023-10-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0026_remove_servicio_estadoservicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='serEstadoServicio',
        ),
        migrations.AlterField(
            model_name='servicioprestado',
            name='serpEstado',
            field=models.CharField(choices=[('Cancelado', 'Cancelado'), ('Solicitado', 'Solicitado'), ('Terminado', 'Terminado'), ('Entregado', 'Entregado'), ('En Proceso', 'En Proceso')], db_comment='Estado del servicio prestado', max_length=15, null=True),
        ),
    ]
