# Generated by Django 4.2.3 on 2023-10-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0028_alter_servicioprestado_serpestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empTerminoServicio',
            field=models.BooleanField(db_comment='Indica si el empleado ha terminado su servicio', default=False),
        ),
    ]
