# Generated by Django 4.2.3 on 2023-10-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0029_empleado_empterminoservicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='empTerminoServicio',
        ),
    ]
