# Generated by Django 4.2.6 on 2023-10-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0031_detalleservicioprestado_detestadoservicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleservicioprestado',
            name='detObservaciones',
            field=models.TextField(db_comment='Observaciones acerca del servicio prestado realizado', null=True),
        ),
    ]
