# Generated by Django 4.2.6 on 2023-10-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0032_detalleservicioprestado_detobservaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleservicioprestado',
            name='detFechaRealizacion',
            field=models.DateTimeField(auto_now_add=True, db_comment='Fecha y Hora de realización del servicio', null=True),
        ),
    ]
