# Generated by Django 4.2.6 on 2023-10-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionServiteca', '0033_detalleservicioprestado_detfecharealizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleservicioprestado',
            name='detFechaRealizacion',
        ),
    ]
